import { compile, shuffleFrame, flip, tiltFrame, trim } from './pixel.js';

/*
 * Art direction (gameplan §6): 24-32px tall, oversized hats, long hair,
 * minimal facial detail, rectangular torsos, heavy ink lines.
 * Rows auto-pad, so grids only need their leading pixels to line up.
 */

const TATA_DOWN = [
  '................',
  '................',
  '.....KKKKKK.....',
  '....KKKKKKKK....',
  '...KKKKKKKKKK...',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  '..kKKKKKKKKKKk..',
  '...KKKSSSSKKK...',
  '...KKKKKKKKKK...',
  '...KKKSSSSKKK...',
  '...KKKSSSSKKK...',
  '...KKKKKKKKKK...',
  '..KKKKKKKKKKKK..',
  '.KKKKWWWWWWKKKK.',
  '.KKKKWWWWWWKKKK.',
  '.KKKKKWWWWKKKKK.',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '...KKKKKKKKKK...',
  '...KKK....KKK...',
  '...KKK....KKK...',
  '...KKK....KKK...',
  '...KKK....KKK...',
  '..KKKK....KKKK..',
  '................',
];

const TATA_UP = [
  '................',
  '................',
  '.....KKKKKK.....',
  '....KKKKKKKK....',
  '...KKKKKKKKKK...',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  '..kKKKKKKKKKKk..',
  '...KKKKKKKKKK...',
  '...KKKKKKKKKK...',
  '...KKKKKKKKKK...',
  '...KKKKKKKKKK...',
  '...KKKKKKKKKK...',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '...KKKKKKKKKK...',
  '...KKK....KKK...',
  '...KKK....KKK...',
  '...KKK....KKK...',
  '...KKK....KKK...',
  '..KKKK....KKKK..',
  '................',
];

const TATA_SIDE = [
  '................',
  '................',
  '....KKKKKKK.....',
  '...KKKKKKKKK....',
  '..KKKKKKKKKKK...',
  'KKKKKKKKKKKKKKK.',
  'KKKKKKKKKKKKKKK.',
  '..kKKKKKKKKKKk..',
  '...KKKKSSSS.....',
  '...KKKKKKKK.....',
  '...KKKKSSSS.....',
  '...KKKKSSSS.....',
  '...KKKKKKKK.....',
  '..KKKKKKKKK.....',
  '..KKKKWWWWKGG...',
  '..KKKKWWWWKGG...',
  '..KKKKKWWKK.....',
  '..KKKKKKKKK.....',
  '..KKKKKKKKK.....',
  '...KKKKKKK......',
  '....KKKKK.......',
  '....KKKKK.......',
  '....KKKKK.......',
  '....KKKKK.......',
  '...KKKKKKK......',
  '................',
];

const TRAVELER_DOWN = [
  '................',
  '................',
  '...KKKKKKKKKK...',
  '..KKKKKKKKKKKK..',
  '.KKKKKKKKKKKKKK.',
  'KKKKKKKKKKKKKKKK',
  '..KKKKKKKKKKKK..',
  '...KKKKKKKKKK...',
  '...KKKKBBKKKK...',
  '...KKKKKKKKKK...',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  '.KK.KK.KK.KK.KK.',
  '................',
];

const TRAVELER_SIDE = [
  '................',
  '................',
  '..KKKKKKKKKK....',
  '.KKKKKKKKKKKK...',
  'KKKKKKKKKKKKKK..',
  'KKKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKK...',
  '..KKKKKKKKKK....',
  '..KKKKKKKKBK....',
  '..KKKKKKKKKK....',
  '..KKKKKKKKKK....',
  '..KKKKKKKKKKK...',
  '.KKKKKKKKKKKK...',
  '.KKKKKKKKKKKK...',
  '.KKKKKKKKKKKK...',
  '.KKKKKKKKKKKK...',
  '.KKKKKKKKKKKK...',
  '.KKKKKKKKKKKK...',
  '.KKKKKKKKKKK....',
  '.KKKKKKKKKKK....',
  '.KKKKKKKKKKK....',
  '.KKKKKKKKKKK....',
  'KKKKKKKKKKKKK...',
  'KKKKKKKKKKKKK...',
  'KKKKKKKKKKKKKK..',
  'KKKKKKKKKKKKKK..',
  '.KK.KK.KK.KK....',
  '................',
];

const NPC_DOWN = [
  '................',
  '................',
  '................',
  '....KKKKKKKK....',
  '..KKKKKKKKKKKK..',
  '..KKKKKKKKKKKK..',
  '....KKKKKKKK....',
  '....KSSSSSSK....',
  '....KKKKKKKK....',
  '....KSSSSSSK....',
  '....KKKKKKKK....',
  '....KWWWWWWK....',
  '...KWWWWWWWWK...',
  '..KKWWWWWWWWKK..',
  '..KKWWWWWWWWKK..',
  '..KKWWWWWWWWKK..',
  '..KKWWWWWWWWKK..',
  '...KWWWWWWWWK...',
  '....KKKKKKKK....',
  '....KKK..KKK....',
  '....KKK..KKK....',
  '....KKK..KKK....',
  '...KKKK..KKKK...',
  '................',
];

const NPC_UP = NPC_DOWN.map((r, i) => (i >= 7 && i <= 10 ? '....KKKKKKKK....' : r));

const NPC_SIDE = [
  '................',
  '................',
  '................',
  '....KKKKKKK.....',
  '..KKKKKKKKKK....',
  '..KKKKKKKKKK....',
  '....KKKKKKK.....',
  '....KKKSSSS.....',
  '....KKKKKKK.....',
  '....KKKSSSS.....',
  '....KKKKKKK.....',
  '....KWWWWWK.....',
  '...KWWWWWWK.....',
  '..KKWWWWWWK.....',
  '..KKWWWWWWK.....',
  '..KKWWWWWWK.....',
  '..KKWWWWWWK.....',
  '...KWWWWWWK.....',
  '....KKKKKK......',
  '....KKKKK.......',
  '....KKKKK.......',
  '....KKKKK.......',
  '...KKKKKKK......',
  '................',
];

const DOG_SIDE = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '..KK............',
  '.KKKKK.KKKKKKK..',
  '.KKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKK.',
  '..KKKKKKKKKKKK..',
  '..KK..KK..KK....',
  '..KK..KK..KK....',
  '..KK..KK..KK....',
  '..KK......KK....',
  '................',
  '................',
];

// --- enemies -------------------------------------------------------------

const LANTERN_WISP = [
  '........................',
  '..........KKKK..........',
  '.........K....K.........',
  '........K......K........',
  '......KKKKKKKKKKKK......',
  '.....KKKKKKKKKKKKKK.....',
  '.....KYYYYYYYYYYYYK.....',
  '.....KYYBBBBBBBBYYK.....',
  '.....KYBBBBBBBBBBYK.....',
  '.....KYBBBKKKKBBBYK.....',
  '.....KYBBBKKKKBBBYK.....',
  '.....KYBBBBBBBBBBYK.....',
  '.....KYYBBBBBBBBYYK.....',
  '.....KYYYYYYYYYYYYK.....',
  '.....KKKKKKKKKKKKKK.....',
  '......KKKKKKKKKKKK......',
  '.......KK......KK.......',
  '........B......B........',
  '.........B....B.........',
  '..........B..B..........',
  '...........BB...........',
  '........................',
  '........................',
  '........................',
];

const CRATE_CRAWLER = [
  '........................',
  '........................',
  '....KKKKKKKKKKKKKK......',
  '....KTTTTTTTTTTTTK......',
  '....KTKKTTTTTTKKTK......',
  '....KTKBTTTTTTBKTK......',
  '....KTKKTTTTTTKKTK......',
  '....KTTTTTTTTTTTTK......',
  '....KTTKKKKKKKKTTK......',
  '....KTTKWWWWWWKTTK......',
  '....KTTKKKKKKKKTTK......',
  '....KTTTTTTTTTTTTK......',
  '....KKKKKKKKKKKKKK......',
  '.....K..K......K..K.....',
  '....KK..KK....KK..KK....',
  '...KK....KK..KK....KK...',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

const RIFT_HOUND = [
  '........................',
  '........................',
  '........................',
  '...KK...............KK..',
  '..KKKK.............KKKK.',
  '..KKKKKK.....KKKKKKKKKK.',
  '.KKKKKKKKKKKKKKKKKKKKKK.',
  '.KKBKKKKKKKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKKKKKKKKKK.',
  '.KKKKKKKKKKKKKKKKKKKKK..',
  '..KKKKKKKKKKKKKKKKKKK...',
  '..KKK..KKK...KKK..KKK...',
  '..KKK..KKK...KKK..KKK...',
  '..KKK..KKK...KKK..KKK...',
  '..KKK..KKK...KKK..KKK...',
  '.KKKK..KKKK.KKKK..KKKK..',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

const LANTERN_KEEPER = [
  '................................',
  '..............KKKK..............',
  '.............K....K.............',
  '............K......K............',
  '.........KKKKKKKKKKKKKK.........',
  '........KKKKKKKKKKKKKKKK........',
  '........KKYYYYYYYYYYYYKK........',
  '........KKYYBBBBBBBBYYKK........',
  '........KKYBBBBBBBBBBYKK........',
  '........KKYBBKKKKKKBBYKK........',
  '........KKYBBKKKKKKBBYKK........',
  '........KKYBBBBBBBBBBYKK........',
  '........KKYYYYYYYYYYYYKK........',
  '........KKKKKKKKKKKKKKKK........',
  '.........KKKKKKKKKKKKKK.........',
  '...........KKKKKKKKKK...........',
  '.........KKKKKKKKKKKKKK.........',
  '.......KKKKKKKKKKKKKKKKKK.......',
  '......KKKKKKKKKKKKKKKKKKKK......',
  '......KKKKKKKKKKKKKKKKKKKK......',
  '......KKKKKWWWWWWWWKKKKKKK......',
  '......KKKKKWWWWWWWWKKKKKKK......',
  '......KKKKKKKKKKKKKKKKKKKK......',
  '......KKKKKKKKKKKKKKKKKKKK......',
  '.......KKKKKKKKKKKKKKKKKK.......',
  '.......KKKKKKKKKKKKKKKKKK.......',
  '.......KKKKKKKKKKKKKKKKKK.......',
  '......KKKKKKKKKKKKKKKKKKKK......',
  '.....KKKKKKKKKKKKKKKKKKKKKK.....',
  '....KKKKKKKKKKKKKKKKKKKKKKKK....',
  '....KK.KK.KK.KK..KK.KK.KK.KK....',
  '................................',
];

const CLOCK_RAT = [
  '........................',
  '........................',
  '........................',
  '........................',
  '.....KK.........KK......',
  '....KKKK.......KKKK.....',
  '....KKKKKKKKKKKKKKK.....',
  '...KKKKKKKKKKKKKKKKK....',
  '...KKGGKKKKKKKKGGKKKK...',
  '...KKGYGKKKKKKGYGKKKKK..',
  '...KKGGKKKKKKKKGGKKKKKK.',
  '...KKKKKKKKKKKKKKKKKKKKK',
  '....KKKKKKKKKKKKKKKKK...',
  '....KK..KK...KK..KK.....',
  '....KK..KK...KK..KK.....',
  '...KKK..KKK.KKK..KKK....',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

const RIFT_STAG = [
  '..K..................K..',
  '..K.K..............K.K..',
  '..KKK..K........K..KKK..',
  '...KK..K.K....K.K..KK...',
  '....KKKKKK....KKKKKK....',
  '.....KKKK......KKKK.....',
  '......KKKKKKKKKKKK......',
  '.......KKKKKKKKKK.......',
  '.......KKBKKKKBKK.......',
  '.......KKKKKKKKKK.......',
  '........KKKKKKKK........',
  '.........KKKKKK.........',
  '.......KKKKKKKKKK.......',
  '.....KKKKKKKKKKKKKK.....',
  '....KKKKKKKKKKKKKKKK....',
  '....KKKKKKKKKKKKKKKK....',
  '....KKKKKKKKKKKKKKKK....',
  '.....KKKKKKKKKKKKKK.....',
  '.....KKK......KKKKK.....',
  '.....KKK......KKKKK.....',
  '.....KKK......KKKKK.....',
  '.....KKK......KKKKK.....',
  '....KKKK......KKKKKK....',
  '........................',
];

const CAPSULE = [
  '................',
  '................',
  '......KKKK......',
  '.....KBBBBK.....',
  '....KBBBBBBK....',
  '....KBBWWBBK....',
  '....KBBWWBBK....',
  '....KBBBBBBK....',
  '.....KBBBBK.....',
  '......KKKK......',
  '................',
  '................',
];

/** Builds the four-direction, two-frame animation set for a character grid trio. */
function actor(down, up, side, { legRows = 5, hatRows = 7 } = {}) {
  const d = compile(down), u = compile(up), s = compile(side);
  return {
    down: [d, shuffleFrame(d, legRows, 1), tiltFrame(d, hatRows, 1)],
    up: [u, shuffleFrame(u, legRows, 1), tiltFrame(u, hatRows, 1)],
    right: [s, shuffleFrame(s, legRows, 1), tiltFrame(s, hatRows, 1)],
    left: [flip(s), flip(shuffleFrame(s, legRows, 1)), flip(tiltFrame(s, hatRows, 1))],
  };
}

export const SPRITES = {};

export function buildSprites() {
  SPRITES.tata = actor(TATA_DOWN, TATA_UP, TATA_SIDE, { legRows: 6, hatRows: 8 });
  SPRITES.traveler = actor(TRAVELER_DOWN, TRAVELER_DOWN, TRAVELER_SIDE, { legRows: 2, hatRows: 8 });
  SPRITES.dog = { down: [compile(DOG_SIDE)], up: [compile(DOG_SIDE)], right: [compile(DOG_SIDE)], left: [flip(compile(DOG_SIDE))] };
  SPRITES.capsule = compile(CAPSULE);

  // NPC colour variants: only the garment key changes, ink stays ink.
  const coats = { villager: '#efe7d7', merchant: '#a5321f', archivist: '#1d5fa8', guard: '#565049', smuggler: '#5d3c21', teacher: '#8a5a32' };
  SPRITES.npc = {};
  for (const [name, hex] of Object.entries(coats)) {
    SPRITES.npc[name] = actor(NPC_DOWN, NPC_UP, NPC_SIDE);
    const ov = { W: hex };
    const d = compile(NPC_DOWN, ov), u = compile(NPC_UP, ov), s = compile(NPC_SIDE, ov);
    SPRITES.npc[name] = {
      down: [d, shuffleFrame(d, 5, 1), tiltFrame(d, 7, 1)],
      up: [u, shuffleFrame(u, 5, 1), tiltFrame(u, 7, 1)],
      right: [s, shuffleFrame(s, 5, 1), tiltFrame(s, 7, 1)],
      left: [flip(s), flip(shuffleFrame(s, 5, 1)), flip(tiltFrame(s, 7, 1))],
    };
  }

  SPRITES.enemy = {
    wisp: trim(compile(LANTERN_WISP)),
    crate: trim(compile(CRATE_CRAWLER)),
    hound: trim(compile(RIFT_HOUND)),
    keeper: trim(compile(LANTERN_KEEPER)),
    rat: trim(compile(CLOCK_RAT)),
    stag: trim(compile(RIFT_STAG)),
  };
}
